name: run tests and coverage reports

on:
  push:
    branches: [main, develop, feat/*, fix/*]
  pull_request:
    branches: [main, develop, feat/*, fix/*]

jobs:
  tests-front-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run tests and generate code coverage report
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: front

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: front/coverage/bobapp
    
  tests-back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: ./back
        
      - name: Run tests and generate jacoco report
        run: mvn test jacoco:report
        working-directory: ./back
  
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco